ktor:
  application:
    modules:
      - mevi.com.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  secret: "mevi"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/"
  realm: "Access to '/'"