ktor:
  application:
    modules:
      - mevi.com.ApplicationKt.module
  deployment:
    port: 8080

storage:
  driverClassName: "org.h2.Driver"
  jdbcURL: "jdbc:h2:file:"
  dbFilePath: build/db
jwt:
  secret: "mevi"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/"
  realm: "Access to '/'"
google_cloud:
  oauth2_authorize_url: ""
  oauth2_access_token_url: ""
  client_id: "client_id"
  client_secret: "client_secret"